### ISSUE TITLE
Problems configuring API_URL in the docker image

### ISSUE THREAD

**Issue by kusold** [Mozart409/blocky-frontend#35]
I keep receiving the following error when I try to submit a lookup: `Error: API_URL is undefined. Please set it in .env file.`

However, when I obtain a shell inside the container, I see that the API_URL environment variable is set:
```
/srv # env | grep API_URL
API_URL=http://blocky.blocky.svc.cluster.local:4000
```

I think the problem is that the API_URL is being read with `process.env.API_URL` when the bundle is being built, and the container is only serving up the already built bundle.

I found some info on the vite website that might be related to this: https://vitejs.dev/guide/env-and-mode.html#production-replacement

It sounds like replacing all `process.env.API_URL` references with `import.meta.env.API_URL` might fix this.

**Comment by Mozart409** [comment]
I will fix that.

**Comment by Mozart409** [comment]
this should be fixed in v0.1.0

**Comment by kusold** [comment]
I'm still encountering this problem with v0.1.1.

In the browser's JS console.
```
Error: API_URL is undefined. Please set it in .env file.
```

From inside the blocky-frontend container:
```
/srv # env | grep API
BLOCKY_API_URL=http://blocky.blocky.svc.cluster.local
BLOCKY_SERVICE_PORT_API=4000
API_URL=http://blocky.blocky.svc.cluster.local
```

**Comment by NeoPlayer13** [comment]
I got the same problem too.
